## Array Creation & Initialization

In [1]:
import numpy as np

- **Create 1D array from 0 to 9.**

In [2]:
arr = np.arange(10)
print("Original array:", arr)

Original array: [0 1 2 3 4 5 6 7 8 9]


- **Create array of 10 zeros.**

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- **Create array of 10 ones.**

In [4]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- **Create array of 10 fives.**

In [5]:
arr = np.full(10, 5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


- **Create array with values 0, 0.1, 0.2, ..., 1.0.**

In [6]:
arr = np.arange(0, 1.1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


- **Create array of 10 log-spaced numbers between 1 and 100.**

In [11]:
arr = np.logspace(0, 2, 10)
print(arr)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


- **Create 3x3 identity matrix**

In [12]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
