## Array Creation & Initialization

In [1]:
import numpy as np

- **Create 1D array from 0 to 9.**

In [2]:
arr = np.arange(10)
print("Original array:", arr)

Original array: [0 1 2 3 4 5 6 7 8 9]


- **Create array of 10 zeros.**

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- **Create array of 10 ones.**

In [4]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- **Create array of 10 fives.**

In [5]:
arr = np.full(10, 5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


- **Create array with values 0, 0.1, 0.2, ..., 1.0.**

In [6]:
arr = np.arange(0, 1.1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


- **Create array of 10 log-spaced numbers between 1 and 100.**

In [7]:
arr = np.logspace(0, 2, 10)
print(arr)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


- **Create 3x3 identity matrix**

In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- **Create a 5x5 array with all values 7.**

In [9]:
arr = np.full((5, 5), 7)
print(arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


- **Create a 2x3 array of random floats between 0 and 1.**

In [10]:
arr = np.random.rand(2, 3)
print(arr)

[[0.73366446 0.9309383  0.58161997]
 [0.14903812 0.46842803 0.87219226]]


- **Create a 2x3 array of random integers between 5 and 15.**

In [11]:
arr = np.random.randint(5, 16, size=(2, 3))
print(arr)

[[15 14  9]
 [ 9  8  8]]


- **Create a 1D array of 20 random numbers from a standard normal distribution.**

In [12]:
rng = np.random.default_rng()
data = rng.standard_normal(20)
print(data)

[-0.83507601  0.48701309 -2.07743906  0.33897551  0.35019385  1.14771716
 -0.57024467 -0.6566055   1.50287148  0.30094905  1.08103819 -0.6083944
 -0.96842385  1.33564931 -1.28519948 -1.64882382 -0.58732579 -0.24538879
 -0.45276873  0.4927344 ]


- **Create a 2D array of shape (4,4) from a list of lists.**

In [13]:
list_of_lists = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]
array_2d = np.array(list_of_lists)
print(array_2d)
print(f"Shape: {array_2d.shape}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)


- **Create an uninitialized array of shape (3,3) of integers.**

In [14]:
uninitialized_array = np.empty((3, 3), dtype=int)
print(uninitialized_array)

[[4607182418800017408                   0                   0]
 [                  0 4607182418800017408                   0]
 [                  0                   0 4607182418800017408]]


- **Create an array of shape (2,2) with dtype complex.**

In [15]:
arr = np.array([[1, 2],
                [3, 4]], dtype=complex)

print(arr)
print(arr.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


- **Create an array of length 10 starting at 5 with step 3.**

In [16]:
arr = np.arange(5, 5 + 10*3, 3)
print(arr)

[ 5  8 11 14 17 20 23 26 29 32]


- **Convert a Python list [2,3,4] into a NumPy array.**

In [17]:
lst = [2, 3, 4]
arr = np.array(lst)

print(arr)

[2 3 4]


- **Create a diagonal array from [1,2,3].**

In [18]:
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


- **Create a 3x3 array with 1 on the border and 0 inside.**

In [19]:
arr = np.ones((3, 3), dtype=int)
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


- **Create a 4x4 array with random integers and copy it to a new variable.**

In [20]:
arr = np.random.randint(0, 10, size=(4, 4))
print("Original array:\n", arr)

# Copy the array to a new variable
arr_copy = arr.copy()
print("\nCopied array:\n", arr_copy)

Original array:
 [[9 2 4 7]
 [4 1 3 8]
 [3 1 4 0]
 [8 9 2 6]]

Copied array:
 [[9 2 4 7]
 [4 1 3 8]
 [3 1 4 0]
 [8 9 2 6]]


- **Create 5x5 array with row values 0-4.**

In [21]:
arr = np.tile(np.arange(5), (5, 1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


- **Create 8x8 checkerboard pattern.**

In [22]:
checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


- **Create 8x8 checkerboard pattern.**

In [23]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


- **Create 100x100 checkerboard pattern.**

In [24]:
checkerboard = np.zeros((20, 20), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


- **Create 3x3x3 random array.**

In [25]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.12411624 0.38878377 0.74955459]
  [0.93752533 0.069687   0.43783269]
  [0.82645674 0.57618179 0.12804728]]

 [[0.42356132 0.0859304  0.89228472]
  [0.16298088 0.47449061 0.81765237]
  [0.68046747 0.20554376 0.99723577]]

 [[0.24564077 0.6182672  0.42913128]
  [0.98955416 0.76505464 0.50994251]
  [0.68065619 0.63281648 0.85393893]]]


- **Create array of dtype uint8 with values 0 and 255.**

In [26]:
arr = np.array([0, 255], dtype=np.uint8)
print(arr)
print(arr.dtype)

[  0 255]
uint8


- **reate 1D array of 100 random Booleans.**

In [27]:
arr = np.random.choice([True, False], size=100)
print(arr)

[False False  True False False False False False  True False  True False
 False False False False False  True  True  True False False False False
 False  True  True  True  True False False False False False  True False
 False False False  True  True False  True  True  True False  True  True
  True  True False False  True  True  True  True False False  True False
  True  True False False  True False False  True  True  True False  True
 False False  True False False False  True  True False  True False  True
 False  True False False False  True  True False False  True False False
  True False  True False]


- **Create 5x5 lower triangular matrix of ones.**

In [28]:
matrix = np.tril(np.ones((5, 5), dtype=int))
print(matrix)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


- **Create Vandermonde matrix from [1,2,3] with 4 columns.**

In [29]:
v = np.array([1, 2, 3])
V = np.vander(v, 4)
print(V)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]


- **Create meshgrid from [0,1,2] and [0,1].**

In [30]:
x = [0, 1, 2]
y = [0, 1]
X, Y = np.meshgrid(x, y)
print("X:")
print(X)
print("Y:")
print(Y)

X:
[[0 1 2]
 [0 1 2]]
Y:
[[0 0 0]
 [1 1 1]]


- **Create 10x10 random array and find min, max.**

In [31]:
# Create 10x10 random array
arr = np.random.rand(10, 10)

# Find minimum and maximum
min_val = arr.min()
max_val = arr.max()

print("Array:\n", arr)
print("\nMinimum value:", min_val)
print("Maximum value:", max_val)

Array:
 [[0.88669755 0.25353884 0.02792934 0.0778017  0.72311323 0.08230231
  0.25128018 0.78599725 0.97983659 0.09688376]
 [0.01008275 0.18474738 0.88794359 0.01483078 0.58474032 0.43601771
  0.99891651 0.68637907 0.22584964 0.51514301]
 [0.29587296 0.1679276  0.73944434 0.59755524 0.36527443 0.35522212
  0.29215348 0.70063807 0.68104609 0.4222896 ]
 [0.51360832 0.14612182 0.26543066 0.3826095  0.29316689 0.84796036
  0.50382725 0.95973074 0.31611405 0.92579458]
 [0.51609007 0.36619485 0.53668446 0.14077733 0.28951058 0.69146122
  0.92337912 0.39227906 0.67864615 0.47426121]
 [0.86972566 0.85216226 0.01576433 0.43488993 0.43898268 0.12420531
  0.45564833 0.51939745 0.25959503 0.58482187]
 [0.75344628 0.942764   0.59899733 0.65826503 0.68598033 0.41893148
  0.45739285 0.69941562 0.5146179  0.20745297]
 [0.10015133 0.72803572 0.3932468  0.95992609 0.24809141 0.07882671
  0.04929883 0.74731944 0.97535849 0.45858434]
 [0.58730472 0.75477898 0.91554463 0.70016631 0.94645133 0.8205081
  0.2

- **Create 10x10 constant array with value 3.14.**

In [32]:
arr = np.full((10, 10), 3.14)
print(arr)

[[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]]


## Array Properties & Attributes

- **Get shape of array arr.**

In [33]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)


- **Get number of dimensions of**

In [34]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.ndim)

2


- **Get total elements in arr.**

In [35]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.size)

6


- **Get dtype of arr.**

In [36]:
arr = np.array([1, 2, 3])
print(arr.dtype)

int64


- **Change dtype from int32 to float64**

In [37]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr = arr.astype(np.float64)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


- **Convert float array to int (truncate).**

In [38]:
arr = np.array([1.9, 2.5, 3.7])
arr_int = arr.astype(int)
print(arr_int)

[1 2 3]


- **Convert array to Python list.**

In [39]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print(arr_list := arr.tolist())

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


- **Get strides of 2D array**

In [40]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.strides)

(24, 8)


- **Check if array owns its data**

In [41]:
arr = np.array([1, 2, 3])
print(arr.flags['OWNDATA'])

True


- **Get base of sliced array.**

In [42]:
arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[1:4]

print(sliced_arr.base)

[1 2 3 4 5]


- **Make deep copy of array**

In [43]:
arr = np.array([1, 2, 3])
arr_copy = arr.copy()
arr[0] = 100
print(arr)       # original array
print(arr_copy) 

[100   2   3]
[1 2 3]


- **Create view and modify to affect original.**

In [44]:
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
view_arr[0] = 100
print("Original array:", arr)
print("View array:", view_arr)

Original array: [100   2   3   4   5]
View array: [100   2   3   4   5]


- **Reshape 1D array of 12 elements to 3x4 (no copy).**

In [45]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)

print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


- **Flatten 2D array to 1D.**

In [46]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.flatten())
print(arr.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


- **Transpose 2D array.**

In [47]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr_T := arr.T)

[[1 4]
 [2 5]
 [3 6]]


- **Swap axes 0 and 1 of 3D array.**

In [48]:
arr = np.random.rand(2, 3, 4)  # 3D array

arr_swapped = arr.swapaxes(0, 1)

print(arr_swapped.shape)

(3, 2, 4)


- **Get real and imaginary parts of complex array.**

In [49]:
arr = np.array([1+2j, 3-4j, 5+6j])

print("Real part:", arr.real)
print("Imaginary part:", arr.imag)

Real part: [1. 3. 5.]
Imaginary part: [ 2. -4.  6.]


- **Change byte order from little to big-endian.**

In [50]:
arr = np.array([1, 256], dtype='<i4')  # little-endian int32

arr_be = arr.byteswap().view(arr.dtype.newbyteorder('>'))

print(arr.dtype)
print(arr_be.dtype)


int32
>i4


- **Create array with copy() and view().**

In [51]:
arr = np.array([1, 2, 3, 4])

# Create a view (shallow copy)
arr_view = arr.view()

# Create a copy (deep copy)
arr_copy = arr.copy()

# Modify view
arr_view[0] = 100

# Modify copy
arr_copy[1] = 200
print("Original array:", arr)
print("View array:", arr_view)
print("Copy array:", arr_copy)

Original array: [100   2   3   4]
View array: [100   2   3   4]
Copy array: [  1 200   3   4]


## Indexing & Slicing

- **Get 3rd element of 1D array.**

In [52]:
arr = np.array([10, 20, 30, 40])

print(arr[2])

30


- **Get element at (2,3) in 2D array.**

In [53]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12]])

print(arr[2, 3])

12


- **Slice 1D array from index 5 to 10.**

In [54]:
arr = np.arange(15)
print(arr[5:10])

[5 6 7 8 9]


- **Get first 3 rows, last 2 columns of 2D array.**

In [ ]:
arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])
result = arr[:3, -2:]
print(result)

[[ 3  4]
 [ 7  8]
 [11 12]]


- **Get every other element of 1D array.**

In [56]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[0 2 4 6]
