## Array Creation & Initialization

In [1]:
import numpy as np

- **Create 1D array from 0 to 9.**

In [2]:
arr = np.arange(10)
print("Original array:", arr)

Original array: [0 1 2 3 4 5 6 7 8 9]


- **Create array of 10 zeros.**

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- **Create array of 10 ones.**

In [4]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- **Create array of 10 fives.**

In [5]:
arr = np.full(10, 5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


- **Create array with values 0, 0.1, 0.2, ..., 1.0.**

In [6]:
arr = np.arange(0, 1.1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


- **Create array of 10 log-spaced numbers between 1 and 100.**

In [7]:
arr = np.logspace(0, 2, 10)
print(arr)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


- **Create 3x3 identity matrix**

In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- **Create a 5x5 array with all values 7.**

In [9]:
arr = np.full((5, 5), 7)
print(arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


- **Create a 2x3 array of random floats between 0 and 1.**

In [10]:
arr = np.random.rand(2, 3)
print(arr)

[[0.57303777 0.32181318 0.01094786]
 [0.0571365  0.49308709 0.46219882]]


- **Create a 2x3 array of random integers between 5 and 15.**

In [11]:
arr = np.random.randint(5, 16, size=(2, 3))
print(arr)

[[11 11 11]
 [11  9  7]]


- **Create a 1D array of 20 random numbers from a standard normal distribution.**

In [12]:
rng = np.random.default_rng()
data = rng.standard_normal(20)
print(data)

[ 0.90099048  0.77691825  0.16252202 -0.38826059  0.64811549 -0.14686807
 -2.14118348 -0.87428231 -1.92723453 -0.36384546  0.18756894  0.70089626
  1.56694705 -0.51335236  0.56373126 -1.49389087  0.0073478  -0.97796638
  0.26218749  0.26930147]


- **Create a 2D array of shape (4,4) from a list of lists.**

In [13]:
list_of_lists = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]
array_2d = np.array(list_of_lists)
print(array_2d)
print(f"Shape: {array_2d.shape}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)


- **Create an uninitialized array of shape (3,3) of integers.**

In [14]:
uninitialized_array = np.empty((3, 3), dtype=int)
print(uninitialized_array)

[[4607182418800017408                   0                   0]
 [                  0 4607182418800017408                   0]
 [                  0                   0 4607182418800017408]]


- **Create an array of shape (2,2) with dtype complex.**

In [15]:
arr = np.array([[1, 2],
                [3, 4]], dtype=complex)

print(arr)
print(arr.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


- **Create an array of length 10 starting at 5 with step 3.**

In [16]:
arr = np.arange(5, 5 + 10*3, 3)
print(arr)

[ 5  8 11 14 17 20 23 26 29 32]


- **Convert a Python list [2,3,4] into a NumPy array.**

In [17]:
lst = [2, 3, 4]
arr = np.array(lst)

print(arr)

[2 3 4]


- **Create a diagonal array from [1,2,3].**

In [18]:
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


- **Create a 3x3 array with 1 on the border and 0 inside.**

In [19]:
arr = np.ones((3, 3), dtype=int)
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


- **Create a 4x4 array with random integers and copy it to a new variable.**

In [20]:
arr = np.random.randint(0, 10, size=(4, 4))
print("Original array:\n", arr)

# Copy the array to a new variable
arr_copy = arr.copy()
print("\nCopied array:\n", arr_copy)

Original array:
 [[2 9 3 2]
 [2 9 8 8]
 [1 5 9 2]
 [0 7 0 4]]

Copied array:
 [[2 9 3 2]
 [2 9 8 8]
 [1 5 9 2]
 [0 7 0 4]]


- **Create 5x5 array with row values 0-4.**

In [21]:
arr = np.tile(np.arange(5), (5, 1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


- **Create 8x8 checkerboard pattern.**

In [22]:
checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


- **Create 8x8 checkerboard pattern.**

In [23]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


- **Create 100x100 checkerboard pattern.**

In [25]:
checkerboard = np.zeros((20, 20), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


- **Create 3x3x3 random array.**

In [26]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.55793582 0.18073263 0.08461308]
  [0.75604489 0.98124462 0.99479101]
  [0.9076798  0.98779067 0.26713218]]

 [[0.13598735 0.90029635 0.60977068]
  [0.9922926  0.74501447 0.45795993]
  [0.25658107 0.07485712 0.70253525]]

 [[0.20801101 0.23769842 0.45403009]
  [0.00386683 0.6161577  0.02644897]
  [0.70023808 0.85711664 0.54550109]]]


- **Create array of dtype uint8 with values 0 and 255.**

In [27]:
arr = np.array([0, 255], dtype=np.uint8)
print(arr)
print(arr.dtype)

[  0 255]
uint8


- **reate 1D array of 100 random Booleans.**

In [30]:
arr = np.random.choice([True, False], size=100)
print(arr)

[False False False False False  True False False False False False False
  True  True  True  True False False False False  True  True  True False
  True False False False  True False False False  True False  True  True
 False False  True False False False False  True False  True  True  True
 False  True  True  True False False  True False False  True  True False
 False False  True  True  True False  True False  True  True False  True
 False  True  True  True False  True  True False False  True False  True
  True False  True False False False  True  True  True False False  True
  True  True False False]


- **Create 5x5 lower triangular matrix of ones.**

In [31]:
matrix = np.tril(np.ones((5, 5), dtype=int))
print(matrix)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
