## Array Creation & Initialization

In [1]:
import numpy as np

- **Create 1D array from 0 to 9.**

In [2]:
arr = np.arange(10)
print("Original array:", arr)

Original array: [0 1 2 3 4 5 6 7 8 9]


- **Create array of 10 zeros.**

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- **Create array of 10 ones.**

In [4]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- **Create array of 10 fives.**

In [5]:
arr = np.full(10, 5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


- **Create array with values 0, 0.1, 0.2, ..., 1.0.**

In [6]:
arr = np.arange(0, 1.1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


- **Create array of 10 log-spaced numbers between 1 and 100.**

In [7]:
arr = np.logspace(0, 2, 10)
print(arr)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


- **Create 3x3 identity matrix**

In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- **Create a 5x5 array with all values 7.**

In [9]:
arr = np.full((5, 5), 7)
print(arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


- **Create a 2x3 array of random floats between 0 and 1.**

In [10]:
arr = np.random.rand(2, 3)
print(arr)

[[0.16400249 0.74966957 0.19517621]
 [0.8795761  0.86743949 0.24231111]]


- **Create a 2x3 array of random integers between 5 and 15.**

In [11]:
arr = np.random.randint(5, 16, size=(2, 3))
print(arr)

[[15 14  6]
 [12 13  5]]


- **Create a 1D array of 20 random numbers from a standard normal distribution.**

In [12]:
rng = np.random.default_rng()
data = rng.standard_normal(20)
print(data)

[ 2.75486434  0.1221248  -0.88383205 -0.69799902  0.55492299 -0.93536903
  0.14679134  0.60754071 -0.59560514 -0.33057867 -0.30980056  0.09173216
 -0.60586338 -0.88079983 -1.06357462 -0.53187863 -0.4215444   0.32673961
 -0.50269534 -0.12554364]


- **Create a 2D array of shape (4,4) from a list of lists.**

In [13]:
list_of_lists = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]
array_2d = np.array(list_of_lists)
print(array_2d)
print(f"Shape: {array_2d.shape}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape: (4, 4)


- **Create an uninitialized array of shape (3,3) of integers.**

In [14]:
uninitialized_array = np.empty((3, 3), dtype=int)
print(uninitialized_array)

[[4607182418800017408                   0                   0]
 [                  0 4607182418800017408                   0]
 [                  0                   0 4607182418800017408]]


- **Create an array of shape (2,2) with dtype complex.**

In [15]:
arr = np.array([[1, 2],
                [3, 4]], dtype=complex)

print(arr)
print(arr.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


- **Create an array of length 10 starting at 5 with step 3.**

In [16]:
arr = np.arange(5, 5 + 10*3, 3)
print(arr)

[ 5  8 11 14 17 20 23 26 29 32]


- **Convert a Python list [2,3,4] into a NumPy array.**

In [17]:
lst = [2, 3, 4]
arr = np.array(lst)

print(arr)

[2 3 4]


- **Create a diagonal array from [1,2,3].**

In [18]:
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


- **Create a 3x3 array with 1 on the border and 0 inside.**

In [19]:
arr = np.ones((3, 3), dtype=int)
arr[1:-1, 1:-1] = 0
print(arr)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


- **Create a 4x4 array with random integers and copy it to a new variable.**

In [20]:
arr = np.random.randint(0, 10, size=(4, 4))
print("Original array:\n", arr)

# Copy the array to a new variable
arr_copy = arr.copy()
print("\nCopied array:\n", arr_copy)

Original array:
 [[7 2 2 8]
 [0 1 5 3]
 [3 5 9 5]
 [8 5 2 6]]

Copied array:
 [[7 2 2 8]
 [0 1 5 3]
 [3 5 9 5]
 [8 5 2 6]]


- **Create 5x5 array with row values 0-4.**

In [21]:
arr = np.tile(np.arange(5), (5, 1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


- **Create 8x8 checkerboard pattern.**

In [22]:
checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


- **Create 8x8 checkerboard pattern.**

In [23]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


- **Create 100x100 checkerboard pattern.**

In [24]:
checkerboard = np.zeros((20, 20), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


- **Create 3x3x3 random array.**

In [25]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.51091715 0.48105538 0.21259727]
  [0.50859054 0.151694   0.32743393]
  [0.35637654 0.25276996 0.6731383 ]]

 [[0.20514898 0.66958125 0.78675678]
  [0.28971047 0.78345824 0.41264562]
  [0.28615708 0.28930142 0.39208147]]

 [[0.9106264  0.52905908 0.93526431]
  [0.93365792 0.01756008 0.51783506]
  [0.75180157 0.71671793 0.45611391]]]


- **Create array of dtype uint8 with values 0 and 255.**

In [26]:
arr = np.array([0, 255], dtype=np.uint8)
print(arr)
print(arr.dtype)

[  0 255]
uint8


- **reate 1D array of 100 random Booleans.**

In [27]:
arr = np.random.choice([True, False], size=100)
print(arr)

[False False  True  True False  True False False  True  True  True False
  True False  True  True False False  True  True  True  True  True False
  True False  True False  True  True  True  True False  True  True False
  True False  True False  True False  True False  True False False False
  True False  True  True  True False  True False  True  True  True  True
  True False  True False False False  True False  True  True  True  True
  True  True False False False  True  True  True False  True  True False
 False  True False  True  True  True  True False False  True  True  True
 False False  True False]


- **Create 5x5 lower triangular matrix of ones.**

In [28]:
matrix = np.tril(np.ones((5, 5), dtype=int))
print(matrix)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


- **Create Vandermonde matrix from [1,2,3] with 4 columns.**

In [29]:
v = np.array([1, 2, 3])
V = np.vander(v, 4)
print(V)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]


- **Create meshgrid from [0,1,2] and [0,1].**

In [30]:
x = [0, 1, 2]
y = [0, 1]
X, Y = np.meshgrid(x, y)
print("X:")
print(X)
print("Y:")
print(Y)

X:
[[0 1 2]
 [0 1 2]]
Y:
[[0 0 0]
 [1 1 1]]


- **Create 10x10 random array and find min, max.**

In [31]:
# Create 10x10 random array
arr = np.random.rand(10, 10)

# Find minimum and maximum
min_val = arr.min()
max_val = arr.max()

print("Array:\n", arr)
print("\nMinimum value:", min_val)
print("Maximum value:", max_val)

Array:
 [[0.21743286 0.32958853 0.5458677  0.44467907 0.46133377 0.07228908
  0.34533274 0.14742469 0.14944112 0.79200425]
 [0.22347747 0.8450555  0.12890117 0.72534452 0.05479726 0.29710991
  0.37698061 0.36987518 0.50075509 0.01145429]
 [0.45082527 0.06990437 0.31535946 0.81303388 0.87440537 0.12564849
  0.00800647 0.08385847 0.35027749 0.44010539]
 [0.28045941 0.36939895 0.74768525 0.95080808 0.91037607 0.99957638
  0.8623723  0.86028667 0.41670387 0.08194248]
 [0.22454205 0.77977243 0.0355673  0.63914947 0.796637   0.24234861
  0.79804003 0.01899037 0.91043706 0.41559795]
 [0.29273898 0.81975845 0.37473035 0.57629257 0.76580557 0.77856185
  0.14051751 0.49967105 0.64233412 0.54926143]
 [0.28837186 0.78533421 0.60440775 0.70120355 0.40699628 0.85842156
  0.82180834 0.61771891 0.40039005 0.30073437]
 [0.4036337  0.83235402 0.06536369 0.5554496  0.79558893 0.34682292
  0.00117425 0.24287727 0.10567272 0.50185192]
 [0.8995229  0.12296571 0.31005037 0.57785535 0.37302675 0.21838947
  0.

- **Create 10x10 constant array with value 3.14.**

In [32]:
arr = np.full((10, 10), 3.14)
print(arr)

[[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]]


## Array Properties & Attributes

- **Get shape of array arr.**

In [33]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)


- **Get number of dimensions of**

In [34]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.ndim)

2


- **Get total elements in arr.**

In [35]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.size)

6


- **Get dtype of arr.**

In [36]:
arr = np.array([1, 2, 3])
print(arr.dtype)

int64


- **Change dtype from int32 to float64**

In [37]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr = arr.astype(np.float64)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


- **Convert float array to int (truncate).**

In [38]:
arr = np.array([1.9, 2.5, 3.7])
arr_int = arr.astype(int)
print(arr_int)

[1 2 3]


- **Convert array to Python list.**

In [39]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print(arr_list := arr.tolist())

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


- **Get strides of 2D array**

In [40]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.strides)

(24, 8)


- **Check if array owns its data**

In [41]:
arr = np.array([1, 2, 3])
print(arr.flags['OWNDATA'])

True


- **Get base of sliced array.**

In [42]:
arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[1:4]

print(sliced_arr.base)

[1 2 3 4 5]


- **Make deep copy of array**

In [43]:
arr = np.array([1, 2, 3])
arr_copy = arr.copy()
arr[0] = 100
print(arr)       # original array
print(arr_copy) 

[100   2   3]
[1 2 3]


- **Create view and modify to affect original.**

In [44]:
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
view_arr[0] = 100
print("Original array:", arr)
print("View array:", view_arr)

Original array: [100   2   3   4   5]
View array: [100   2   3   4   5]


- **Reshape 1D array of 12 elements to 3x4 (no copy).**

In [45]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)

print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


- **Flatten 2D array to 1D.**

In [46]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.flatten())
print(arr.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


- **Transpose 2D array.**

In [47]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr_T := arr.T)

[[1 4]
 [2 5]
 [3 6]]


- **Swap axes 0 and 1 of 3D array.**

In [48]:
arr = np.random.rand(2, 3, 4)  # 3D array

arr_swapped = arr.swapaxes(0, 1)

print(arr_swapped.shape)

(3, 2, 4)


- **Get real and imaginary parts of complex array.**

In [49]:
arr = np.array([1+2j, 3-4j, 5+6j])

print("Real part:", arr.real)
print("Imaginary part:", arr.imag)

Real part: [1. 3. 5.]
Imaginary part: [ 2. -4.  6.]


- **Change byte order from little to big-endian.**

In [50]:
arr = np.array([1, 256], dtype='<i4')  # little-endian int32

arr_be = arr.byteswap().view(arr.dtype.newbyteorder('>'))

print(arr.dtype)
print(arr_be.dtype)


int32
>i4


- **Create array with copy() and view().**

In [51]:
arr = np.array([1, 2, 3, 4])

# Create a view (shallow copy)
arr_view = arr.view()

# Create a copy (deep copy)
arr_copy = arr.copy()

# Modify view
arr_view[0] = 100

# Modify copy
arr_copy[1] = 200
print("Original array:", arr)
print("View array:", arr_view)
print("Copy array:", arr_copy)

Original array: [100   2   3   4]
View array: [100   2   3   4]
Copy array: [  1 200   3   4]


## Indexing & Slicing

- **Get 3rd element of 1D array.**

In [52]:
arr = np.array([10, 20, 30, 40])

print(arr[2])

30


- **Get element at (2,3) in 2D array.**

In [53]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12]])

print(arr[2, 3])

12


- **Slice 1D array from index 5 to 10.**

In [54]:
arr = np.arange(15)
print(arr[5:10])

[5 6 7 8 9]


- **Get first 3 rows, last 2 columns of 2D array.**

In [55]:
arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])
result = arr[:3, -2:]
print(result)

[[ 3  4]
 [ 7  8]
 [11 12]]


- **Get every other element of 1D array.**

In [56]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[0 2 4 6]


- **Reverse 1D array using slicing.**

In [57]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


- **Get all rows, second column of 2D array.**

In [58]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

second_column = arr[:, 1]

print(second_column)

[2 5 8]


- **Extract 1st, 3rd, 4th elements using integer indexing.**

In [59]:
arr = np.array([10, 20, 30, 40, 50])

extracted_elements = arr[[0, 2, 3]]

print(extracted_elements)

[10 30 40]


- **Extract elements >5 using Boolean indexing.**

In [60]:
arr = np.array([1, 4, 6, 2, 9, 3, 8])

result = arr[arr > 5]

print(result)

[6 9 8]


- **Set all elements <0 to 0.**

In [61]:
arr = np.array([3, -1, 5, -7, 2, -4])

arr[arr < 0] = 0

print(arr)

[3 0 5 0 2 0]


- **Extract rows where column 0 > 5.**

In [62]:
arr = np.array([[2, 3, 4],
                [6, 7, 8],
                [9, 1, 2],
                [4, 5, 6]])

result = arr[arr[:, 0] > 5]

print(result)

[[6 7 8]
 [9 1 2]]


- **Use fancy indexing to shuffle array rows.**

In [63]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
shuffled_indices = np.random.permutation(arr.shape[0])
shuffled_arr = arr[shuffled_indices]
print(shuffled_arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


- **Get diagonal elements of square matrix.**

In [64]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Get diagonal elements
diagonal_elements = np.diag(arr)

print(diagonal_elements)

[1 5 9]


- **Extract anti-diagonal elements.**

In [65]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Extract anti-diagonal elements
anti_diagonal = np.fliplr(arr).diagonal()

print(anti_diagonal)

[3 5 7]


- **Get corner elements of 2D array.**

In [66]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
top_left = arr[0, 0]
top_right = arr[0, -1]
bottom_left = arr[-1, 0]
bottom_right = arr[-1, -1]
corners = np.array([top_left, top_right, bottom_left, bottom_right])
print(corners)

[1 3 7 9]


- **Extract every 3rd element starting from index 1.**

In [67]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extract every 3rd element starting from index 1
result = arr[1::3]

print(result)

[ 1  4  7 10]


- **Get array of indices where condition is True.**

In [ ]:
arr = np.array([3, 7, 2, 9, 5, 1, 8])
indices = np.where(arr > 5)
print(indices)

(array([1, 3, 6]),)


- **Use np.where() to replace values.**

In [69]:
arr = np.array([2, 5, 8, 3, 10, 1])

# Replace values greater than 5 with 0
result = np.where(arr > 5, 0, arr)

print(result)

[2 5 0 3 0 1]


- **Extract values between two thresholds.**

In [70]:
arr = np.array([1, 4, 6, 8, 10, 3, 7])

# Extract values between two thresholds (greater than 4 and less than 9)
result = arr[(arr > 4) & (arr < 9)]

print(result)

[6 8 7]


- **Select random subset of array elements.**

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
subset = np.random.choice(arr, size=3, replace=False)
print(subset)

[10 60 30]


- **Get last row of 2D array**

In [72]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Get last row
last_row = arr[-1]

print(last_row)

[7 8 9]


- **Get all but last column.**

In [73]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Get all rows, all but last column
result = arr[:, :-1]

print(result)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


- **Get second last element of 1D array.**

In [74]:
arr = np.array([10, 20, 30, 40, 50])

# Get second last element
second_last = arr[-2]

print(second_last)

40


- **Extract 2x2 block from center of 5x5 array.**

In [75]:
arr = np.arange(1, 26).reshape(5, 5)

# Extract 2x2 block from the center
center_block = arr[2:4, 2:4]

print(center_block)

[[13 14]
 [18 19]]


- **Get cross-section of 3D array at z=2.**

In [76]:
arr = np.arange(3 * 4 * 5).reshape(3, 4, 5)

# Get cross-section at z = 2
cross_section = arr[:, :, 2]

print(cross_section)

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]


- **Use np.take() to get elements at indices [0,2,4].**

In [77]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Get elements at indices [0, 2, 4]
result = np.take(arr, [0, 2, 4])

print(result)

[10 30 50]


- **Use np.compress() to get elements where condition True.**

In [ ]:
arr = np.array([3, 7, 2, 9, 5, 1])
# Condition (elements greater than 4)
condition = arr > 4
# Use np.compress to extract elements where condition is True
result = np.compress(condition, arr)
print(result)

[7 9 5]


- **Use np.select() with multiple conditions.**

In [79]:
# Sample array
arr = np.array([3, 7, 2, 9, 5, 1])

# Define conditions
conditions = [
    arr < 3,       # Condition 1
    (arr >= 3) & (arr <= 6),  # Condition 2
    arr > 6        # Condition 3
]

# Corresponding choices for each condition
choices = ['low', 'medium', 'high']

# Use np.select to assign values based on conditions
result = np.select(conditions, choices, default='unknown')

print(result)

['medium' 'high' 'low' 'high' 'medium' 'low']


- **Extract non-zero elements.**

In [80]:
# Sample array
arr = np.array([0, 3, 0, 7, 2, 0, 5])

# Extract non-zero elements
non_zero_elements = arr[arr != 0]

print(non_zero_elements)

[3 7 2 5]


- **Get unique rows from 2D array.**

In [81]:
arr = np.array([[1, 2],
                [3, 4],
                [1, 2],
                [5, 6]])

# Get unique rows
unique_rows = np.unique(arr, axis=0)

print(unique_rows)

[[1 2]
 [3 4]
 [5 6]]


- **Sort array and get corresponding indices.**

In [ ]:
arr = np.array([50, 20, 40, 10, 30])
# Get sorted array
sorted_arr = np.sort(arr)
# Get indices that would sort the array
sorted_indices = np.argsort(arr)
print("Sorted array:", sorted_arr)
print("Indices of sorted elements:", sorted_indices)

Sorted array: [10 20 30 40 50]
Indices of sorted elements: [3 1 4 2 0]


- **Get top 5 largest values.**

In [83]:
arr = np.array([10, 50, 20, 70, 30, 90, 40])

# Get indices of top 5 largest values
top5_indices = np.argsort(arr)[-5:][::-1]

# Get top 5 largest values
top5_values = arr[top5_indices]

print(top5_values)

[90 70 50 40 30]


- **Partition array around kth element.**

In [84]:
arr = np.array([10, 50, 20, 70, 30, 90, 40])

k = 3  # Partition around 3rd index (0-based)

# Partition the array
partitioned_arr = np.partition(arr, k)

print(partitioned_arr)

[10 20 30 40 50 70 90]


- **Use np.argpartition() to get indices of smallest 3 elements.**

In [85]:
# Sample array
arr = np.array([50, 20, 40, 10, 30, 60, 70])

# Get indices of the smallest 3 elements
indices_smallest3 = np.argpartition(arr, 3)[:3]

print(indices_smallest3)

[3 1 4]


- **Get indices of diagonal in flattened array.**

[3 1 4]


In [87]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Number of columns
n = arr.shape[1]

# Indices of diagonal in flattened array
diagonal_indices = np.arange(0, arr.size, n+1)

print(diagonal_indices)

[0 4 8]


## Array Operations & Mathematics


- **Add two arrays element-wise.**

In [88]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
result = arr1 + arr2

print(result)

[5 7 9]


- **Subtract, multiply, divide two arrays.**

In [89]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 5, 3])

# Element-wise subtraction
sub = arr1 - arr2

# Element-wise multiplication
mul = arr1 * arr2

# Element-wise division
div = arr1 / arr2

print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)








Subtraction: [ 8 15 27]
Multiplication: [ 20 100  90]
Division: [ 5.  4. 10.]
